default:
  image: python:3.8-slim

stages:
  - qa
  - test

lint:
  stage: qa
  before_script:
    - pip install flake8
  script:
    - python -m flake8

unittest:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest
