repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
      - id: mypy
        files: src
        additional_dependencies: [pydantic==1.6.1]
  -   repo: https://github.com/timothycrosley/isort
      rev: 5.1.3
      hooks:
      - id: isort
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        language_version: python3.8
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
      - id: flake8
