version: '3.8'

services:
  autopoetry:
    image: autopoetry:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.alpine
      args:
        - target=release
    ports:
    - "8000:8000"
